# Example external files configuration
# This file demonstrates how to group related file monitoring configurations
# You can include this file in your main config using:
#   external_files = ["monitoring-group-example.toml"]

# External files can contain [[files]], [[commands]], and [[processes]] sections
# Other sections (like time_periods, default_interval, etc.) are not allowed

# Example: Monitor development files
# Interval can be specified using time format: "1s", "2m", "3h", "0.5s"
[[files]]
path = "src/main.py"
command = "python -m pytest tests/"
interval = "2s"

[[files]]
path = "src/utils.py"
command = "python -m pylint src/utils.py"

[[files]]
path = "tests/test_main.py"
command = "python -m pytest tests/test_main.py -v"

# Example: Monitor configuration files
[[files]]
path = "config/settings.json"
command = "python validate_config.py"

[[files]]
path = "config/database.yml"
command = "systemctl reload myapp"

# Example: Periodic commands (using [[commands]] section for clarity)
# These execute periodically without monitoring any specific file
[[commands]]
command = "python cleanup_temp.py"
interval = "1h"

[[commands]]
command = "./backup_data.sh"
interval = "6h"

# Example: Process monitoring (using [[processes]] section for clarity)
# These monitor and terminate processes without executing commands
[[processes]]
terminate_if_process = "runaway_process"
interval = "5m"
