name: Ruff Code Quality Check

on:
  pull_request_target:
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'ruff.toml'
      - '.github/workflows/ruff-check.yml'
  push:
    branches:
      - main
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'ruff.toml'
      - '.github/workflows/ruff-check.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: |
          pip install ruff>=0.6.0

      - name: Auto-format code with Ruff
        run: |
          ruff format src/
          ruff check --fix src/

      - name: Commit formatting changes
        if: github.event_name == 'pull_request_target'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Auto-format code with Ruff [skip ci]"
            git push
          else
            echo "No formatting changes needed"
          fi

      - name: Run Ruff check
        run: |
          ruff check src/

      - name: Run Ruff format check
        run: |
          ruff format --check src/
